#!/bin/sh
alias  java=/usr/local/java/jdk1.6.0_30/bin/java
alias javac=/usr/local/java/jdk1.6.0_30/bin/javac
export JAVA_HOME=/usr/local/java/jdk1.6.0_30
echo "JAVA_HOME: $JAVA_HOME"
echo "java -version:"
java -version