#!/bin/sh
alias  java=/usr/local/java/jdk1.7.0/bin/java
alias javac=/usr/local/java/jdk1.7.0/bin/javac
JAVA_HOME=/usr/local/java/jdk1.7.0
echo "JAVA_HOME: $JAVA_HOME"
echo "java -version:"
java -version